# Generated by Django 3.0.5 on 2020-04-28 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('url', models.CharField(max_length=2048)),
                ('verification_id', models.CharField(max_length=36)),
                ('verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawl.Site')),
            ],
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Page'), (2, 'External'), (3, 'Other')])),
                ('url', models.CharField(max_length=2048)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'OK'), (2, 'Timeout'), (3, 'HTTP Error')])),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_time', models.PositiveIntegerField()),
                ('error', models.CharField(blank=True, max_length=255, null=True)),
                ('links', models.ManyToManyField(blank=True, related_name='pages', to='crawl.Link')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawl.Scan')),
            ],
        ),
    ]
