# Generated by Django 3.0.5 on 2020-05-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'OK'), (2, 'TIMEOUT'), (3, 'HTTP_ERROR')]),
        ),
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PAGE'), (2, 'EXTERNAL'), (3, 'OTHER')]),
        ),
    ]
