# Generated by Django 3.0.5 on 2020-05-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0002_auto_20200506_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='last_verify_error',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
