# Generated by Django 3.0.5 on 2020-06-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0004_auto_20200603_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
