# Generated by Django 3.0.5 on 2020-07-07 10:11

from django.db import migrations


def forwards(apps, schema_editor):
    if schema_editor.connection.alias != "default":
        return

    UserProfile = apps.get_model("crawl", "UserProfile")
    User = apps.get_model("auth", "User")
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user)


class Migration(migrations.Migration):

    dependencies = [
        ("crawl", "0006_userprofile"),
    ]

    operations = [
        migrations.RunPython(forwards),
    ]
