# Generated by Django 3.0.5 on 2020-07-15 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0007_create_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'PAGE'), (2, 'EXTERNAL'), (3, 'OTHER'), (4, 'NON_WEB')]),
        ),
    ]
