# Generated by Django 3.0.5 on 2020-07-16 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0011_update_proxy_permissions"),
        ("crawl", "0008_auto_20200715_2031"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupSettings",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("max_sites", models.IntegerField(default=10)),
                ("group", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="auth.Group")),
            ],
        ),
    ]
