# Generated by Django 3.0.5 on 2020-07-07 10:11

from django.db import migrations


def forwards(apps, schema_editor):
    if schema_editor.connection.alias != "default":
        return

    GroupSettings = apps.get_model("crawl", "GroupSettings")
    Group = apps.get_model("auth", "Group")

    group, created = Group.objects.get_or_create(name="Basic")
    GroupSettings.objects.get_or_create(group=group)

    if created:
        User = apps.get_model("auth", "User")
        for user in User.objects.all():
            user.groups.add(group)


class Migration(migrations.Migration):

    dependencies = [
        ("crawl", "0009_groupsettings"),
    ]

    operations = [
        migrations.RunPython(forwards, lambda *args, **kwargs: None),
    ]
