# Generated by Django 3.0.5 on 2020-07-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0011_groupsettings_recrawl_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupsettings',
            name='recrawl_schedule',
            field=models.CharField(default='0 18 * * 0', help_text="<a href='https://en.wikipedia.org/wiki/Cron'>cron format</a>", max_length=63),
        ),
    ]
