# Generated by Django 3.0.5 on 2020-07-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0012_auto_20200723_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scan',
            options={'permissions': (('can_start_scan', 'Can start manual scan'),)},
        ),
    ]
