# Generated by Django 3.0.5 on 2020-07-29 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0013_auto_20200724_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('h1_first', models.TextField()),
                ('h1_second', models.TextField()),
                ('h2_first', models.TextField()),
                ('h2_second', models.TextField()),
                ('link', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crawl.Link')),
            ],
        ),
    ]
