# Generated by Django 3.0.5 on 2020-08-04 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0015_auto_20200729_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='size',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
