# Generated by Django 3.0.5 on 2020-08-20 20:23

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0016_link_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_before', models.DateTimeField()),
                ('not_after', models.DateTimeField()),
                ('common_name', models.TextField()),
                ('organization', models.TextField()),
                ('dns_names', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), default=list, size=None)),
                ('issuer_organization', models.TextField()),
                ('issuer_cn', models.TextField()),
                ('cipher_suite', models.CharField(max_length=128)),
                ('version', models.CharField(max_length=8)),
                ('errors', django.contrib.postgres.fields.jsonb.JSONField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='tls_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'NONE'), (2, 'OK'), (3, 'ERROR')], default=1),
        ),
        migrations.AddField(
            model_name='link',
            name='tls',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crawl.Tls'),
        ),
    ]
