# Generated by Django 3.0.5 on 2020-09-03 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0017_auto_20200820_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'permissions': (('can_see_page_size', 'Can see page size'), ('can_see_images', 'Can see images'), ('can_see_seo', 'Can see seo'))},
        ),
    ]
