# Generated by Django 3.0.5 on 2020-09-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0018_auto_20200903_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'OK'), (2, 'TIMEOUT'), (3, 'HTTP_ERROR'), (4, 'OTHER_ERROR'), (5, 'TOO_MANY_REDIRECTS')]),
        ),
    ]
