# Generated by Django 3.0.5 on 2020-09-11 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0018_auto_20200903_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='email_sent',
            field=models.BooleanField(default=True),
        ),
    ]
