# Generated by Django 3.0.5 on 2020-09-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0019_scan_email_sent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scan',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
