# Generated by Django 3.0.5 on 2020-10-07 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0019_auto_20200924_1613'),
        ('crawl', '0020_auto_20200911_0511'),
    ]

    operations = [
    ]
