# Generated by Django 3.0.5 on 2020-10-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0021_merge_20201007_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='cached_num_non_tls_images',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='cached_num_non_tls_scripts',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='cached_num_non_tls_stylesheets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='cached_num_tls_images',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='cached_num_tls_scripts',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='cached_num_tls_stylesheets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='cached_tls_images',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='cached_tls_scripts',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='cached_tls_stylesheets',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='cached_tls_total',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
