# Generated by Django 3.0.5 on 2020-10-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0022_auto_20201015_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='cached_size_images',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='cached_size_scripts',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='cached_size_stylesheets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='cached_size_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
