# Generated by Django 3.0.5 on 2020-11-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0025_fifoentry_fiforelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='cached_image_occurences',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='cached_link_occurences',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='cached_script_occurences',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='cached_stylesheet_occurences',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
