# Generated by Django 3.0.5 on 2020-11-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0026_auto_20201118_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='large_page_size_threshold',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='large_page_size_threshold',
            field=models.PositiveIntegerField(default=1048576),
        ),
    ]
