# Generated by Django 3.0.5 on 2020-11-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0027_auto_20201126_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='large_page_size_threshold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='last_verify_error',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
