# Generated by Django 3.0.5 on 2020-12-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0030_auto_20201130_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsettings',
            name='uptime_schedule',
            field=models.CharField(default='0 * * * *', help_text="<a href='https://en.wikipedia.org/wiki/Cron'>cron format</a>", max_length=63),
        ),
    ]
