# Generated by Django 3.0.5 on 2021-02-09 09:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0034_linkimage_alt_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='fiforelation',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
