# Generated by Django 3.0.5 on 2021-02-25 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crawl", "0037_auto_20210219_1251"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="LinkLink",
                    fields=[
                        (
                            "id",
                            models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
                        ),
                        (
                            "from_link",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE, related_name="link_links", to="crawl.Link"
                            ),
                        ),
                        (
                            "to_link",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                related_name="source_link_links",
                                to="crawl.Link",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "crawl_link_links",
                        "unique_together": {("from_link", "to_link")},
                    },
                ),
                migrations.AlterField(
                    model_name="link",
                    name="links",
                    field=models.ManyToManyField(
                        blank=True, related_name="pages", through="crawl.LinkLink", to="crawl.Link"
                    ),
                ),
            ]
        )
    ]
