# Generated by Django 3.0.5 on 2021-03-16 09:45

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0038_auto_20210225_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField()),
                ('scan_id', models.PositiveIntegerField(unique=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawl.Site')),
            ],
        ),
    ]
