# Generated by Django 3.0.5 on 2021-04-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0039_scanarchive'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='cached_num_images',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='cached_num_links',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='cached_num_non_ok_images',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='cached_num_non_ok_links',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='cached_num_non_ok_scripts',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='cached_num_non_ok_stylesheets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='cached_num_ok_images',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='cached_num_ok_links',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='cached_num_ok_scripts',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='cached_num_ok_stylesheets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='cached_num_scripts',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='cached_num_stylesheets',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
