# Generated by Django 3.0.5 on 2021-04-19 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0040_auto_20210415_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='cached_is_image',
        ),
        migrations.RemoveField(
            model_name='link',
            name='cached_is_link',
        ),
        migrations.RemoveField(
            model_name='link',
            name='cached_is_script',
        ),
        migrations.RemoveField(
            model_name='link',
            name='cached_is_stylesheet',
        ),
    ]
