# Generated by Django 3.0.5 on 2021-04-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0041_auto_20210419_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiforelation',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
