# Generated by Django 3.0.5 on 2021-04-26 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("crawl", "0043_drop_link_links_id"),
    ]

    operations = [
        migrations.RunSQL("ALTER TABLE crawl_link_images DROP COLUMN id"),
        migrations.RunSQL("ALTER TABLE crawl_link_scripts DROP COLUMN id"),
        migrations.RunSQL("ALTER TABLE crawl_link_stylesheets DROP COLUMN id"),
    ]
