# Generated by Django 3.0.5 on 2021-05-06 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0044_drop_link_other_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='email_sent',
        ),
    ]
