# Generated by Django 3.0.5 on 2021-05-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0045_remove_scan_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupsettings',
            name='recrawl_frequency',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Daily'), (2, 'Weekly')], default=2),
        ),
    ]
