# Generated by Django 3.1.12 on 2021-06-16 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0047_scancache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scancache',
            name='scan',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='crawl.scan'),
        ),
    ]
