# Generated by Django 3.1.12 on 2021-07-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crawl", "0048_auto_20210616_0841"),
    ]

    operations = [
        migrations.AddField(
            model_name="site",
            name="deleted_at",
            field=models.DateTimeField(null=True, blank=True),
        ),
    ]
