# Generated by Django 3.2.6 on 2021-08-10 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_create_teams_for_existing_users'),
        ('crawl', '0049_site_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
