# Generated by Django 3.2.6 on 2021-08-10 13:15

from django.db import migrations


def forwards_func(apps, schema_editor):
    Site = apps.get_model("crawl", "Site")
    for site in Site.objects.all():
        if not site.team_id:
            site.team_id = site.user.membership_set.first().team_id
            site.save()


class Migration(migrations.Migration):

    dependencies = [
        ("crawl", "0050_site_team"),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
