# Generated by Django 3.2.6 on 2021-08-10 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_create_teams_for_existing_users'),
        ('crawl', '0051_assign_team_to_sites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
