# Generated by Django 3.2.6 on 2021-08-18 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20210812_1538'),
        ('crawl', '0052_alter_site_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crawl_config', to='teams.team'),
        ),
    ]
