# Generated by Django 3.2.6 on 2021-08-18 09:59

from django.db import migrations


def forwards_func(apps, schema_editor):
    UserProfile = apps.get_model("crawl", "UserProfile")
    for up in UserProfile.objects.all():
        if not up.team_id:
            up.team_id = up.user.membership_set.first().team_id
            up.save()


class Migration(migrations.Migration):

    dependencies = [
        ("crawl", "0053_userprofile_team"),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
