# Generated by Django 3.2.6 on 2021-08-18 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20210812_1538'),
        ('crawl', '0056_rename_userprofile_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='config',
            name='user',
        ),
        migrations.AlterField(
            model_name='config',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_config', to='teams.team'),
        ),
    ]
