# Generated by Django 3.2.6 on 2021-09-09 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0058_alter_site_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupSettings',
        ),
    ]
