# Generated by Django 3.2.7 on 2021-09-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0060_remove_site_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'permissions': (('can_manage_site', 'Can manage site'),)},
        ),
    ]
