# Generated by Django 3.2.7 on 2021-10-06 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0061_alter_site_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'permissions': (('can_manage_site', 'Can manage site'), ('can_see_all_sites', 'Can see all sites'))},
        ),
    ]
