# Generated by Django 3.2.7 on 2021-10-19 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0062_alter_site_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='resolved_duplicate_description',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='resolved_duplicate_title',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='resolved_missing_alts',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='resolved_missing_description',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='resolved_missing_h1_first',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='resolved_missing_h1_second',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='resolved_missing_h2_first',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='resolved_missing_h2_second',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='resolved_missing_title',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='resolved_size',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='resolved_status',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='link',
            name='resolved_tls',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
