# Generated by Django 3.0.5 on 2020-08-28 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.Subscription')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='user_subscription', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
