# Generated by Django 3.0.5 on 2020-08-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='stripe_id',
            field=models.CharField(default='', max_length=63),
            preserve_default=False,
        ),
    ]
