# Generated by Django 3.0.5 on 2020-09-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_stripecustomer'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'WAITING_PAYMENT'), (2, 'PAYMENT_FAILED'), (3, 'PAID')], default=1),
        ),
    ]
