# Generated by Django 3.0.5 on 2020-09-02 16:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_usersubscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
