# Generated by Django 3.0.5 on 2020-09-03 16:14

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_subscription_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='features',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None),
        ),
    ]
