# Generated by Django 3.0.5 on 2020-09-29 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('payments', '0007_auto_20200903_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
