# Generated by Django 3.0.5 on 2020-09-29 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_auto_20200929_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='name',
            field=models.CharField(default='Monthly', max_length=63),
            preserve_default=False,
        ),
    ]
