# Generated by Django 3.0.5 on 2021-01-04 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_subscription_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='cancel_at',
            field=models.DateTimeField(null=True),
        ),
    ]
