# Generated by Django 3.2.6 on 2021-08-18 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_auto_20210219_1251'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
