# Generated by Django 3.2.6 on 2021-08-18 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20210812_1538'),
        ('payments', '0013_alter_usersubscription_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
