# Generated by Django 3.2.6 on 2021-08-18 08:45

from django.db import migrations


def forwards_func(apps, schema_editor):
    StripeCustomer = apps.get_model("payments", "StripeCustomer")
    for sc in StripeCustomer.objects.all():
        if not sc.team_id:
            sc.team_id = sc.user.membership_set.first().team_id
            sc.save()


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0016_stripecustomer_team"),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
