# Generated by Django 3.2.6 on 2021-08-18 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20210812_1538'),
        ('payments', '0017_assign_team_to_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscription',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.team'),
        ),
    ]
