# Generated by Django 3.2.6 on 2021-08-18 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('payments', '0018_alter_usersubscription_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscription',
            new_name='SubscriptionType',
        ),
        migrations.RenameField(
            model_name='usersubscription',
            old_name='subscription',
            new_name='subscription_type',
        ),
    ]
