# Generated by Django 3.2.6 on 2021-08-18 09:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0005_auto_20210812_1538'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0019_auto_20210818_0859'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserSubscription',
            new_name='Subscription',
        ),
    ]
