# Generated by Django 3.2.6 on 2021-08-18 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0022_auto_20210818_0927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stripecustomer',
            name='user',
        ),
    ]
