# Generated by Django 3.2.6 on 2021-08-26 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_alter_team_plan'),
        ('payments', '0025_alter_stripecustomer_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptiontype',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.plan'),
        ),
    ]
