# Generated by Django 3.2.6 on 2021-08-26 07:51

from django.db import migrations


def forwards_func(apps, schema_editor):
    SubscriptionType = apps.get_model("payments", "SubscriptionType")
    for st in SubscriptionType.objects.all():
        st.plan = st.group.plan
        st.save()


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0026_subscriptiontype_plan"),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
