# Generated by Django 3.2.6 on 2021-09-09 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0028_remove_subscriptiontype_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
    ]
