# Generated by Django 3.2.7 on 2021-09-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0029_remove_subscription_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscription',
            options={'permissions': (('can_manage_subscription', 'Can manage subscription, stripe, payment'),)},
        ),
    ]
