# Generated by Django 3.2.5 on 2021-08-10 10:01

from django.db import migrations
from teams import models


def forwards_func(apps, schema_editor):
    MembershipType = apps.get_model("teams", "MembershipType")
    Group = apps.get_model("auth", "Group")
    group, _ = Group.objects.get_or_create(name="MembershipType - Owner")
    MembershipType.objects.get_or_create(id=models.MembershipType.OWNER, group=group)


def reverse_func(apps, schema_editor):
    MembershipType = apps.get_model("teams", "MembershipType")
    membership = MembershipType.objects.get(id=models.MembershipType.OWNER)
    membership.group.delete()
    membership.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
