# Generated by Django 3.2.5 on 2021-08-10 10:27

from django.contrib.auth.models import User
from django.db import migrations
from teams.models import Team


def forwards_func(apps, schema_editor):
    for user in User.objects.all():
        if not user.membership_set.exists():
            Team.objects.create_default(user)


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0002_add_owner"),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
