# Generated by Django 3.2.6 on 2021-08-26 07:17

from django.db import migrations
from ..models import Plan as RealPlanModel


def forwards_func(apps, schema_editor):
    Plan = apps.get_model("teams", "Plan")
    Team = apps.get_model("teams", "Team")
    Group = apps.get_model("auth", "Group")
    for team in Team.objects.all():
        try:
            membership = team.membership_set.first()
            if membership is None:
                plan = Plan.objects.get(pk=RealPlanModel.BASIC)
            else:
                plan = membership.user.groups.filter(name__startswith="Plan - ").first().plan
        except Group.DoesNotExist:
            plan = Plan.objects.get(pk=RealPlanModel.BASIC)
        team.plan = plan
        team.save()


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0007_add_plans"),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
