# Generated by Django 3.2.6 on 2021-08-26 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_alter_team_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='max_sites',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='plan',
            name='recrawl_frequency',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Daily'), (2, 'Weekly')], default=2),
        ),
        migrations.AddField(
            model_name='plan',
            name='recrawl_schedule',
            field=models.CharField(default='0 18 * * 0', help_text="<a href='https://en.wikipedia.org/wiki/Cron'>cron format</a>", max_length=63),
        ),
        migrations.AddField(
            model_name='plan',
            name='uptime_schedule',
            field=models.CharField(default='0 * * * *', help_text="<a href='https://en.wikipedia.org/wiki/Cron'>cron format</a>", max_length=63),
        ),
    ]
