# Generated by Django 3.2.6 on 2021-08-26 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_copy_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
