# Generated by Django 3.2.7 on 2021-09-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_team_deleted_at'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('user', 'team'), name='membership_unique_user_team'),
        ),
    ]
