# Generated by Django 3.2.7 on 2021-09-29 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0014_invitation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'permissions': (('can_manage_membership', 'Can manage team'),)},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': (('can_manage_team', 'Can manage team'), ('can_delete_team', 'Can delete team'))},
        ),
    ]
