# Generated by Django 3.2.7 on 2021-09-29 15:54

from django.db import migrations
from teams import models


def forwards_func(apps, schema_editor):
    MembershipType = apps.get_model("teams", "MembershipType")
    Group = apps.get_model("auth", "Group")
    group, _ = Group.objects.get_or_create(name="MembershipType - Member")
    MembershipType.objects.get_or_create(id=models.MembershipType.MEMBER, group=group)
    group, _ = Group.objects.get_or_create(name="MembershipType - Client")
    MembershipType.objects.get_or_create(id=models.MembershipType.CLIENT, group=group)


def reverse_func(apps, schema_editor):
    MembershipType = apps.get_model("teams", "MembershipType")
    membership = MembershipType.objects.get(id=models.MembershipType.MEMBER)
    membership.group.delete()
    membership.delete()
    membership = MembershipType.objects.get(id=models.MembershipType.CLIENT)
    membership.group.delete()
    membership.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0015_auto_20210929_1452"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
