# Generated by Django 3.2.7 on 2021-09-29 15:57

from django.db import migrations

permissions = {
    "MembershipType - Owner": [
        "can_manage_site",
        "can_manage_subscription",
        "can_manage_team",
        "can_delete_team",
        "can_manage_membership",
    ],
    "MembershipType - Member": [
        "can_manage_site",
        "can_manage_team",
    ],
}


def forwards_func(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    for name, perms in permissions.items():
        group = Group.objects.get(name=name)
        for codename in perms:
            perm = Permission.objects.get(codename=codename)
            group.permissions.add(perm)


class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0016_add_member_and_client"),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
