# Generated by Django 3.2.7 on 2021-09-29 15:57

from django.db import migrations
from django.contrib.auth.management import create_permissions

permissions = {
    "MembershipType - Owner": [
        "can_manage_site",
        "can_manage_subscription",
        "can_manage_team",
        "can_delete_team",
        "can_manage_membership",
    ],
    "MembershipType - Member": [
        "can_manage_site",
        "can_manage_team",
    ],
}


def forwards_func(apps, schema_editor):
    for app_config in apps.get_app_configs():
        app_config.models_module = True
        create_permissions(app_config, verbosity=0)
        app_config.models_module = None

    Group = apps.get_model("auth", "Group")
    Permission = apps.get_model("auth", "Permission")
    for name, perms in permissions.items():
        group = Group.objects.get(name=name)
        for codename in perms:
            perm = Permission.objects.get(codename=codename)
            group.permissions.add(perm)


class Migration(migrations.Migration):

    dependencies = [
        ("crawl", "0061_alter_site_options"),
        ("payments", "0030_alter_subscription_options"),
        ("teams", "0016_add_member_and_client"),
    ]

    operations = [
        migrations.RunPython(forwards_func),
    ]
