# Generated by Django 3.2.7 on 2021-09-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0017_membership_default_perms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershiptype',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Owner'), (2, 'Member'), (3, 'Client')], primary_key=True, serialize=False),
        ),
    ]
