# Generated by Django 3.2.7 on 2021-10-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0062_alter_site_options'),
        ('teams', '0019_add_see_all_sites_to_membership_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='sites',
            field=models.ManyToManyField(blank=True, to='crawl.Site'),
        ),
    ]
