# Generated by Django 3.2.7 on 2021-10-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawl', '0062_alter_site_options'),
        ('teams', '0020_membership_sites'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='sites',
            field=models.ManyToManyField(blank=True, to='crawl.Site'),
        ),
    ]
