# Generated by Django 3.0.5 on 2020-12-17 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crawl', '0031_groupsettings_uptime_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='UptimeStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'OK'), (2, 'TIMEOUT'), (3, 'HTTP_ERROR'), (4, 'OTHER_ERROR'), (5, 'TOO_MANY_REDIRECTS')])),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_time', models.PositiveIntegerField()),
                ('error', models.CharField(blank=True, max_length=255, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawl.Site')),
            ],
        ),
        migrations.AddIndex(
            model_name='uptimestat',
            index=models.Index(fields=['site', 'created_at'], name='uptime_upti_site_id_f4c617_idx'),
        ),
    ]
