# Generated by Django 3.0.5 on 2021-02-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uptime', '0002_auto_20210204_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uptimestat',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'OK'), (2, 'TIMEOUT'), (3, 'HTTP_ERROR'), (4, 'OTHER_ERROR'), (5, 'TOO_MANY_REDIRECTS'), (6, 'TLS_ERROR')]),
        ),
    ]
