# Generated by Django 3.0.5 on 2020-12-30 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='token',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
